apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-operator-index
  namespace: openshift-marketplace
spec:
  image: lab-registry.snoacm.lab.diktio.net/nsatsia/redhat/redhat-operator-index:v4.10
  sourceType: grpc
